cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'
urlpatterns = [
    path('', views.cars, name='cars'),
    path('<int:id>/car_detail', views.car_detail, name='car_detail'),
    path('search/', views.search, name='search')
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('socialaccount/', include('allauth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services')
]

cars/models.py
from django.db import models
from django.utils.timezone import datetime
from ckeditor.fields import RichTextField
from multiselectfield import MultiSelectField


class Car(models.Model):
    state_choice = (
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('DC', 'District Of Columbia'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        ('IL', 'Illinois'),
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming'),
    )
    year_choice = []
    for r in range(2000, (datetime.now().year + 1)):
        year_choice.append((r, r))

    features_choices = (
        ('Cruise Control', 'Cruise Control'),
        ('Audio Interface', 'Audio Interface'),
        ('Airbags', 'Airbags'),
        ('Air Conditioning', 'Air Conditioning'),
        ('Seat Heating', 'Seat Heating'),
        ('Alarm System', 'Alarm System'),
        ('ParkAssist', 'ParkAssist'),
        ('Power Steering', 'Power Steering'),
        ('Reversing Camera', 'Reversing Camera'),
        ('Direct Fuel Injection', 'Direct Fuel Injection'),
        ('Auto Start/Stop', 'Auto Start/Stop'),
        ('Wind Deflector', 'Wind Deflector'),
        ('Bluetooth Handset', 'Bluetooth Handset'),
    )

    door_choices = (
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
    )

    car_title = models.CharField(max_length=255)
    state = models.CharField(choices=state_choice, max_length=100)
    city = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField(('year'), choices=year_choice)
    condition = models.CharField(max_length=100)
    price = models.IntegerField()
    description = RichTextField()
    car_photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    car_photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    car_photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    features = MultiSelectField(choices=features_choices)
    body_style = models.CharField(max_length=100)
    engine = models.CharField(max_length=100)
    transmission = models.CharField(max_length=100)
    interior = models.CharField(max_length=100)
    doors = models.PositiveIntegerField()
    passengers = models.PositiveIntegerField()
    vin_no = models.CharField(max_length=100, unique=True)
    mileage = models.IntegerField()
    miles = models.IntegerField()
    fuel_type = models.CharField(max_length=120)
    number_of_owners = models.CharField(max_length=120)
    is_featured = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.car_title

cars/views.py
from django.shortcuts import render, get_object_or_404
from .models import Car
from django.core.paginator import Paginator


def cars(request):
    cars = Car.objects.order_by('-created_date').all()
    paginator = Paginator(cars, 4)
    page = request.GET.get('page')
    paged_cars = paginator.get_page(page)
    model_search = Car.objects.values_list('model', flat=True).distinct()
    city_search = Car.objects.values_list('city', flat=True).distinct()
    year_search = Car.objects.values_list('year', flat=True).distinct()
    body_style = Car.objects.values_list('body_style', flat=True).distinct()
    data = {
        'cars': paged_cars,
        'model_search': model_search,
        'city_search': city_search,
        'year_search': year_search,
        'body_style': body_style,
    }
    return render(request, 'cars/cars.html', data)


def car_detail(request, id):
    single_car = get_object_or_404(Car, pk=id)
    data = {
        'single_car': single_car
    }
    return render(request, 'cars/car_detail.html', data)


def search(request):
    all_cars = Car.objects.order_by('-created_date')
    model_search = Car.objects.values_list('model', flat=True).distinct()
    city_search = Car.objects.values_list('city', flat=True).distinct()
    year_search = Car.objects.values_list('year', flat=True).distinct()
    body_style = Car.objects.values_list('body_style', flat=True).distinct()
    transmission_search = Car.objects.values_list('transmission', flat=True).distinct()
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            all_cars = all_cars.filter(description__icontains=keyword)
    if 'model' in request.GET:
        model = request.GET['model']
        if model:
            all_cars = all_cars.filter(model__iexact=model)
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            all_cars = all_cars.filter(city__iexact=city)
    if 'year' in request.GET:
        year = request.GET['year']
        if year:
            all_cars = all_cars.filter(year__iexact=year)
    if 'body_style' in request.GET:
        body_style = request.GET['body_style']
        if body_style:
            all_cars = all_cars.filter(body_style__iexact=body_style)
    if 'min_price' in request.GET:
        min_price = request.GET['min_price']
        max_price = request.GET['max_price']
        if max_price:
           all_cars = all_cars.filter(price__gte=min_price, price__lte=max_price)
    if 'transmission' in request.GET:
        transmission = request.GET['transmission']
        if transmission:
            all_cars = Car.objects.filter(transmission__iexact=transmission)
    data = {
        'all_cars': all_cars,
        'model_search': model_search,
        'city_search': city_search,
        'year_search': year_search,
        'body_style': body_style,
        'transmission_search': transmission_search,
    }
    return render(request, 'cars/search.html', data)

cars/templates/cars/cars.html
{% extends 'base.html' %}

{% block title %}Cars Inventory{% endblock %}

{% block content %}

{% load humanize %}
    <!-- Sub banner start -->
    <div class="sub-banner overview-bgi">
        <div class="container breadcrumb-area">
            <div class="breadcrumb-areas">
                <h1>Our Car Inventory</h1>
                <ul class="breadcrumbs">
                    <li><a href="{% url 'pages:home' %}">Home</a></li>
                    <li class="active">Cars</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Sub Banner end -->

<!-- Featured car start -->
<div class="featured-car content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    {% for car in cars %}
                    <div class="col-lg-6 col-md-6">
                        <div class="car-box-3">
                            <div class="car-thumbnail">
                                <a href="{% url 'cars:car_detail' car.id %}" class="car-img">
                                    <div class="tag">For Rent</div>
                                    <div class="price-box">
                                        <span>{{ car.price | intcomma }}</span>
                                    </div>
                                    <img class="d-block w-100" src="{{ car.car_photo.url }}" alt="car" style="max-height: 262px; min-height: 262px;">
                                </a>
                                <div class="carbox-overlap-wrapper">
                                    <div class="overlap-box">
                                        <div class="overlap-btns-area">
                                            <div class="car-magnify-gallery">
                                                <a href="{{ car.car_photo.url }}" class="overlap-btn">
                                                    <i class="fa fa-expand"></i>
                                                    <img class="hidden" src="{{ car.car_photo.url }}">
                                                </a>
                                                {% if car.car_photo_1 %}
                                                <a href="{{ car.car_photo_1.url }}" class="hidden" >
                                                    <img class="hidden" src="{{ car.car_photo_1.url }}">
                                                </a>
                                                {% endif %}
                                                {% if car.car_photo_2 %}
                                                <a href="{{ car.car_photo_2.url }}" class="hidden">
                                                    <img class="hidden" src="{{ car.car_photo_2.url }}">
                                                </a>
                                                {% endif %}
                                                {% if car.car_photo_3 %}
                                                <a href="{{ car.car_photo_3.url }}" class="hidden">
                                                    <img class="hidden" src="{{ car.car_photo_3.url }}">
                                                </a>
                                                {% endif %}
                                                {% if car.car_photo_4 %}
                                                <a href="{{ car.car_photo_4.url }}" class="hidden" >
                                                    <img class="hidden" src="{{ car.car_photo_4.url }}">
                                                </a>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="detail">
                                <h1 class="title">
                                    <a href="{% url 'cars:car_detail' car.id %}">{{ car.car_title }}</a>
                                </h1>
                                <div class="location">
                                    <a href="{% url 'cars:car_detail' car.id %}">
                                        <i class="flaticon-pin"></i>{{ car.state }} {{ car.city }}
                                    </a>
                                </div>
                                <ul class="facilities-list clearfix">
                                    <li>{{ car.fuel_type }}</li>
                                    <li>{{ car.miles| intcomma }} KM</li>
                                    <li>{{ car.transmission }}</li>
                                    <li>{{ car.body_style }}</li>
                                    <li>{{ car.color }}</li>
                                    <li>{{ car.year }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- Page navigation start -->
                <div class="pagination-box p-box-2 text-center">
                    <nav aria-label="Page navigation example">
                        {% if cars.has_other_pages %}
                        <ul class="pagination">
                            {% if cars.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1"><i class="fa"></i>&laquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fa fa-angle-double-left"></i></a>
                            </li>
                            {% endif %}
                            {% if cars.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ cars.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fa fa-angle-left"></i></a>
                            </li>
                            {% endif %}
                            {% for i in cars.paginator.page_range %}
                                {% if cars.number == i %}
                            <li class="page-item"><a class="page-link active" href="#">{{ i }}</a></li>
                                {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if cars.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ cars.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fa fa-angle-right"></i></a>
                            </li>
                            {% endif %}
                            {% if cars.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ cars.paginator.num_pages }}"><i class="fa"></i>&raquo;</a>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"><i class="fa fa-angle-double-right"></i></a>
                            </li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </nav>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="sidebar-right">
                    <!-- Advanced search start -->
                    <div class="widget advanced-search2">
                        <h3 class="sidebar-title">Search your desire car</h3>
           <form action="{% url 'cars:search' %}" method="">
                <div class="form-group">
                    <input type="text" name="keyword" placeholder="Search by name" class="form-control">
                </div>
                <div class="form-group">
                    <select class="form-control search-fields" name="model">
                        <option selected="true" disabled="disabled" >Model</option>
                        {% for model in model_search %}
                            <option value="{{ model }}">{{ model }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control search-fields" name="city">
                        <option selected="true" disabled="disabled">Location</option>
                        {% for city in city_search %}
                            <option value="{{ city }}">{{ city }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control search-fields" name="year">
                        <option selected="true" disabled="disabled">Year</option>
                        {% for year in year_search %}
                            <option value="{{ year }}">{{ year }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <select class="form-control search-fields" name="body_style">
                        <option selected="true" disabled="disabled">Select Type Of Car</option>
                        {% for body in body_style %}
                            <option value="{{ body }}">{{ body }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="range-slider clearfix">
                                <label>Price</label>
                                <div data-min="0" data-max="150000"  data-min-name="min_price" data-max-name="max_price" data-unit="USD" class="range-slider-ui ui-slider" aria-disabled="false"></div>
                                <div class="clearfix"></div>
                            </div>
                <div class="form-group">
                    <button class="btn btn-block button-theme btn-md">
                        <i class="fa fa-search"></i> Search
                    </button>
                </div>
            </form>
                    </div>

                    <!-- Question start -->
                    <div class="widget question widget-3">
                        <h5 class="sidebar-title">Follow us</h5>
                        <div class="social-list clearfix">
                            <ul>
                                <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#" class="rss-bg"><i class="fa fa-rss"></i></a></li>
                                <li><a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featured car end -->

{% endblock %}

cars/templates/cars/search.html
{% extends 'base.html' %}

{% block title %}Search{% endblock %}

{% block content %}

{% load humanize %}


    <!-- Banner start -->
    <div class="sub-banner overview-bgi">
        <div class="container breadcrumb-area">
            <div class="breadcrumb-areas">
                <h1>Search Results</h1>
                <ul class="breadcrumbs">
                    <li><a href="{% url 'pages:home' %}">Home</a></li>
                    <li class="active">Search</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Banner end -->

    <!-- Search box 3 start -->
    <div class="search-box-3 sb-7 bg-active">
        <div class="container">
            <div class="search-area-inner">
                <div class="search-contents">
                    <form method="GET" action="{% url 'cars:search' %}">
                        <div class="row">
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <select class="selectpicker search-fields" name="Model">
                                        <option disabled="disabled" selected="selected">Select Model</option>
                                          {% for model in model_search %}
                                                <option value="{{ model }}">{{ model }}</option>
                                            {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <select class="selectpicker search-fields" name="city">
                                        <option disabled="disabled" selected="selected">Select City</option>
                                        {% for city in city_search %}
                                            <option value="{{ city }}">{{ city }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <select class="selectpicker search-fields" name="year">
                                        <option disabled="disabled" selected="selected">Select Year</option>
                                        {% for year in year_search %}
                                            <option value="{{ year }}">{{ year }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <select class="selectpicker search-fields" name="body_style">
                                        <option disabled="disabled" selected="selected">Select Body_Style</option>
                                        {% for body in body_style %}
                                            <option value="{{ body }}">{{ body }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <select class="selectpicker search-fields" name="transmission">
                                        <option disabled="disabled" selected="selected">Transmission</option>
                                        {% for transmission in transmission_search %}
                                            <option value="{{ transmission }}">{{ transmission }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <div class="range-slider">
                                        <div data-min="0" data-max="150000" data-unit="USD" data-min-name="min_price" data-max-name="max_price" class="range-slider-ui ui-slider" aria-disabled="false"></div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-6 col-sm-6 col-6">
                                <div class="form-group">
                                    <button class="btn btn-block button-theme btn-md">
                                        <i class="fa fa-search"></i>Find
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Search box 3 end -->

    <!-- Featured car start -->
    <div class="featured-car content-area">
        <div class="container">
            <!-- Main title -->
            <div class="main-title">
                <h1>Here's your <span>Cars</span></h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
            <div class="row">
            {% for all_car in all_cars %}
            <div class="col-lg-4 col-md-6">
                <div class="car-box">
                    <div class="car-thumbnail">
                        <a href="{% url 'cars:car_detail' all_car.id %}" class="car-img">
                            <div class="tag">For Sale</div>
                            <img class="d-block w-100" src="{{ all_car.car_photo.url }}" alt="car" style="min-height: 262px; max-height: 262px;">
                            <div class="facilities-list clearfix">
                                <ul>
                                    <li>
                                        <span><i class="flaticon-way"></i></span>{{ all_car.mileage | intcomma }}km
                                    </li>
                                    <li>
                                        <span><i class="flaticon-calendar-1"></i></span>{{ all_car.year }}
                                    </li>
                                    <li>
                                        <span><i class="flaticon-manual-transmission"></i></span>{{ all_car.transmission }}
                                    </li>
                                </ul>
                            </div>
                        </a>
                        <div class="carbox-overlap-wrapper">
                            <div class="overlap-box">
                                <div class="overlap-btns-area">
                                    <div class="car-magnify-gallery">
                                        {% if all_car.car_photo_1 %}
                                        <a href="{{ all_car.car_photo_1.url }}" class="overlap-btn">
                                            <i class="fa fa-expand"></i>
                                            <img class="hidden" src="{{ all_car.car_photo_1.url }}">
                                        </a>
                                        {% endif %}
                                        {% if all_car.car_photo_2 %}
                                        <a href="{{ all_car.car_photo_2.url }}" class="hidden">
                                            <img class="hidden" src="{{ all_car.car_photo_2.url }}">
                                        </a>
                                        {% endif %}
                                        {% if all_car.car_photo_3 %}
                                        <a href="{{ all_car.car_photo_3.url }}" class="hidden">
                                            <img class="hidden" src="{{ all_car.car_photo_3.url }}">
                                        </a>
                                        {% endif %}
                                        {% if all_car.car_photo_4 %}
                                        <a href="{{ all_car.car_photo_4.url }}" class="hidden">
                                            <img class="hidden" src="{{ all_car.car_photo_4.url }}">
                                        </a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="detail">
                        <h1 class="title">
                            <a href="{% url 'cars:car_detail' all_car.id %}">{{ all_car.car_title }}</a>
                        </h1>
                        <div class="location">
                            <a href="{% url 'cars:car_detail' all_car.id %}">
                                <i class="flaticon-pin"></i>{{ all_car.state }} {{ all_car.city }}
                            </a>
                        </div>
                    </div>
                    <div class="footer clearfix">
                        <div class="pull-left ratings days">
                            <p class="cartype">{{ all_car.body_style }}n</p>
                        </div>
                        <div class="pull-right">
                            <p class="price">{{ all_car.price | intcomma }}$</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
    <!-- Featured car end -->


{% endblock %}